server:
  port: 8080

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/authserver
    username: root
    password:
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
  redis:
    host: 192.168.1.37

authorization-server:
  login-url: /signin
  private-key-path: private.key
  public-key-path: public.json
  issuer: http://localhost:${server.port}
  access-token:
    default-format: jwt
    lifetime: 10m
  id-token:
    lifetime: 10m
  refresh-token:
    lifetime: 8h
    max-lifetime: 8h